import type { CanonicalView } from './types.js';
import { KIND_LABELS, stateLabel } from './canonical.js';
import { isPublicHttpsUrl } from './validation.js';

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
}

/** Deterministic, script-free rendering. The input is the same revision as JSON. */
export function renderReportHtml(view: CanonicalView): string {
  const esc = escapeHtml;
  const citations = (keys: string[]) => keys.map(key => `<a href="#source-${esc(key)}">[${esc(key)}]</a>`).join(' ');
  const sections = view.answer.map(section => `<section><h2>${esc(section.heading)}</h2>${section.body ? `<p>${esc(section.body)}</p>` : ''}<ul>${section.bullets.map(bullet => `<li>${bullet.validity === 'review' ? '<strong class="review">待复核 · </strong>' : ''}${esc(bullet.text)} <small>${esc(KIND_LABELS[bullet.kind])} ${citations(bullet.sourceKeys)}</small></li>`).join('')}</ul></section>`).join('');
  const observations = view.observations.length ? `<section><h2>有据可查的观察</h2><ul>${view.observations.map(item => `<li>${item.validity === 'review' ? '<strong class="review">待复核 · </strong>' : ''}${esc(item.statement)} <small>${esc(KIND_LABELS[item.kind])} ${citations(item.sourceKeys)}</small>${item.limitations.length ? `<p class="muted">${item.limitations.map(esc).join('；')}</p>` : ''}</li>`).join('')}</ul></section>` : '';
  const sources = view.sources.map(source => `<article id="source-${esc(source.sourceKey)}"><h3>[${esc(source.sourceKey)}] ${esc(source.title)}</h3><p class="muted">${source.excluded ? '已撤下 · 依赖此来源的结论需要复核' : source.identityConfirmed ? '人物关联已确认' : '人物关联待核查'} · ${esc(source.fetchStatus)} · ${esc(source.retrievedAt)}</p>${isPublicHttpsUrl(source.url) ? `<a href="${esc(source.url)}" rel="noreferrer noopener">${esc(source.url)}</a>` : '<p>链接不可用</p>'}${source.excerpt ? `<blockquote>${esc(source.excerpt)}</blockquote><small>${esc(source.excerptLocator ?? '来源摘录')}</small>` : ''}${source.limits.length ? `<p class="muted">${source.limits.map(esc).join('；')}</p>` : ''}</article>`).join('');
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${esc(view.identity.displayName || view.question)} · StripSearch</title><style>
*{box-sizing:border-box}body{font-family:system-ui,-apple-system,"Noto Sans CJK SC",sans-serif;color:#252b27;background:#fff;margin:0;line-height:1.8;font-size:15px}main{max-width:800px;margin:56px auto;padding:0 28px}header{border-bottom:2px solid #214d3b;padding-bottom:24px;margin-bottom:32px}h1{font-size:32px;line-height:1.3;margin:12px 0}h2{font-size:22px;margin-top:36px}h3{font-size:16px}p,li,blockquote{overflow-wrap:anywhere}li{margin:12px 0}small,.muted{color:#657069;font-size:12px}a{color:#275940;overflow-wrap:anywhere}blockquote{border-left:3px solid #c3d3c9;margin:12px 0;padding:8px 18px;background:#f7faf8;white-space:pre-wrap;font-size:13px}article{border-top:1px solid #dde4df;padding:14px 0}.review{color:#94571f}.status{font-size:13px;color:#42594b}footer{margin-top:36px;padding-top:20px;border-top:1px solid #dde4df;font-size:12px;color:#657069}@page{size:A4;margin:18mm}@media print{main{margin:0;padding:0}body{font-size:11px}h1{font-size:26px}h2{font-size:18px}article,li{break-inside:avoid}a{color:inherit;text-decoration:none}blockquote{font-size:10px}}
</style></head><body><main><header><small>STRIPSEARCH · 人物研究</small><h1>${esc(view.identity.displayName || '人物研究')}</h1><p>${esc(view.question)}</p><p class="status">${esc(stateLabel(view.state))} · 修订 ${view.revision} · ${esc(view.updatedAt)}</p>${view.identity.note ? `<p class="muted">${esc(view.identity.note)}</p>` : ''}${view.stopReason ? `<p>${esc(view.stopReason)}</p>` : ''}</header>${sections}${observations}${view.limitations.length ? `<section><h2>仍待了解</h2><ul>${view.limitations.map(item => `<li>${esc(item)}</li>`).join('')}</ul></section>` : ''}<section><h2>来源与证据</h2>${sources || '<p>暂无可采用的来源。</p>'}</section><footer>本文件是保存时的资料快照，自述与推断不等同于独立核实。<br>报告 ${esc(view.runId)} · 修订 ${view.revision} · ${esc(view.schemaVersion)}</footer></main></body></html>`;
}
